name: 部署文档

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 必须 20+
          cache: 'pnpm'

      - name: Build docs
        run: |
          pnpm run docs:build
          touch docs/.vuepress/dist/.nojekyll # 确保创建

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
          clean: true # 清理旧文件